spring.datasource.url=jdbc:mysql://localhost:3306/hospito_db
spring.datasource.username=root
spring.datasource.password=<replace_with_your_SQL_password>

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
